/**
 * Build script to generate content_bundle.js for Chrome Extension content scripts.
 */

import fs from 'fs';
import path from 'path';

const contentDir = path.resolve('extension/content');

const selectorsCode = fs.readFileSync(path.join(contentDir, 'selectors.js'), 'utf-8')
  .replace(/export\s+/g, '');

const extractorCode = fs.readFileSync(path.join(contentDir, 'extractor.js'), 'utf-8')
  .replace(/export\s+/g, '');

const domDriverCode = fs.readFileSync(path.join(contentDir, 'dom_driver.js'), 'utf-8')
  .replace(/import\s+.*?;/g, '')
  .replace(/export\s+/g, '');

const observerCode = fs.readFileSync(path.join(contentDir, 'observer.js'), 'utf-8')
  .replace(/import\s+.*?;/g, '')
  .replace(/export\s+/g, '');

const mainCode = fs.readFileSync(path.join(contentDir, 'content_main.js'), 'utf-8')
  .replace(/import\s+.*?;/g, '');

const bundle = `/**
 * ImageGenPiper Content Script Bundle (Self-contained)
 * Auto-generated by scripts/build_extension.js
 */

(function() {
  'use strict';

  // --- Selectors ---
  ${selectorsCode}

  // --- Extractor ---
  ${extractorCode}

  // --- DOM Driver ---
  ${domDriverCode}

  // --- Observer ---
  ${observerCode}

  // --- Content Main ---
  ${mainCode}

})();
`;

fs.writeFileSync(path.join(contentDir, 'content_bundle.js'), bundle, 'utf-8');
console.log('✅ Generated extension/content/content_bundle.js successfully.');
